version: '3.4'

services:
  catalogdb:
    image: mongo

  mockoonapi:
    image: ${DOCKER_REGISTRY-}mockoonwebapi
    build:
      context: .
      dockerfile: ComponentTests.Mockoon/Dockerfile

  componenttests.webapi:
    image: ${DOCKER_REGISTRY-}componenttestswebapi
    build:
      context: .
      dockerfile: ComponentTests.WebApi/Dockerfile